version: "3.4"
services:
############################################################################
  bettersploit:
    hostname: bettersploit
    build:
      context: ./bettersploit
    env_file:
        - ./postgres/database.env # postgres creds
    networks:
      - inbound
    restart: unless-stopped
    depends_on:
      - postgres
#########################################################################
  postgres:
        image: postgres:12
        restart: unless-stopped
        env_file:
          - ./postgres/database.env # configure postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        networks:
          - inbound
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./postgres/main_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./postgres/postgresql.conf:/etc/postgresql/12/main/postgresql.conf
#########################################################################

networks:
      inbound:
volumes:
  postgres-data: