version: "3.4"
services:
############################################################################
  bettersploit:
    hostname: bettersploit
    build:
      context: ./bettersploit
    networks:
      - inbound
    ports:
      - "5432:5432"
    restart: unless-stopped
#########################################################################
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

networks:
      inbound:
volumes:
  database-data: # named volumes can be managed easier using docker-compose