version: "3.4"
services:
############################################################################
  bettersploit:
    hostname: bettersploit
    build:
      context: ./bettersploit
    networks:
      - inbound
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
      inbound:
