version: "3.4"
services:
############################################################################
  bettersploit:
    hostname: bettersploit
    build:
      context: ./bettersploit
    env_file:
        - database.env # postgres creds
    networks:
      - inbound
    ports:
      - "5432:5432"
    restart: unless-stopped
    depends_on:
      - postgres
#########################################################################
  postgres:
        image: postgres:10.5
        restart: unless-stopped
        env_file:
          - database.env # configure postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        networks:
          - inbound
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#########################################################################

networks:
      inbound:
volumes:
  postgres-data: